version: '3.9'
services:
  web:
    build: .
    volumes:
      - .:/app
    command: mix phx.server
    environment:
      DBUSER: mative
      DBPASSWORD: 123456
      DBNAME: mative_dev
      DBPORT: 5432
      DBHOST: db
    ports:
      - '4000:4000'
    depends_on:
      - db
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - mative_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=mative_dev"
      - "POSTGRES_USER=mative"
      - "POSTGRES_PASSWORD=123456"

volumes:
  mative_data:
